apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  selector:
    app: grpc-server
  ports:
  - protocol: TCP
    port: {{ .Values.server.service.port }}
    targetPort: {{ .Values.server.service.targetPort }}
  type: {{ .Values.server.service.type }}

